# Config-Oriented Markup Language (COML)

PORT 3000
HOST 127.0.0.1

HOST

PORT: 4000


names: Max Denis Bob
fruits: apple banana peach


url https://{HOST}:{PORT}/api

[prod]

[dev]
server:

    $PORT

    HOST:
    127.0.0.1
    0.0.0.0