# Config-Oriented Markup Language (COML)
# @env: .env
# :env: PORT, HOST

PORT 3000
HOST 127.0.0.1
HOST 3000

PORT: 4000


names: Max Denis Rob
fruits: apple banana peach


url https://{HOST}:{PORT}/api

[prod]

[dev]
server:

    $PORT

    HOST:
    127.0.0.1
    0.0.0.0